### ISSUE TITLE
missing 25.0.6 static bin

### ISSUE THREAD

**Issue by zhangguanzhang** [docker/docker-ce-packaging#1048]
https://download.docker.com/linux/static/stable/x86_64/
https://github.com/moby/moby/releases/tag/v25.0.6

**Comment by tianon** [comment]
See https://github.com/moby/moby/blob/1c282d1f1b90ff188a1b46f48548ac3151ca2ddf/project/BRANCHES-AND-TAGS.md -- only v27 will have new builds published by Docker Inc via this repository / download.docker.com (and when v28 is released, builds of v27 will likely also cease).

**Comment by zhangguanzhang** [comment]
> See https://github.com/moby/moby/blob/1c282d1f1b90ff188a1b46f48548ac3151ca2ddf/project/BRANCHES-AND-TAGS.md -- only v27 will have new builds published by Docker Inc via this repository / download.docker.com (and when v28 is released, builds of v27 will likely also cease).

Generally speaking, even-numbered versions are lts, ​​but the ones in the list don't seem to conform to this rule. 🤔

**Comment by tianon** [comment]
Someone from Docker's runtime team might correct me, but as far as I'm aware, _none_ of the builds currently published by / versions currently supported by this team have any amount of what could be called Long Term Support.

(In general, there are some projects that follow "even is LTS" but it's certainly not universal :sweat_smile:)
