### ISSUE TITLE
Not possible to build docker from scratch ?

### ISSUE THREAD

**Issue by buczek** [docker/docker-ce-packaging#756]
It looks to me like this tool requires docker already being available on the build system.

If so, the README should mention that. And if there is a way at all to build docker-ce from source only without using precompiled static binaries, a hint would be nice, too.

```
buczek@theinternet:~/git/docker-ce-packaging (master)$ make static
./scripts/checkout.sh src/github.com/docker/cli "HEAD"
+ SRC=src/github.com/docker/cli
+ REF=HEAD
[...]
+ git -C src/github.com/docker/scan-cli-plugin checkout -q refs/tags/v0.17.0
for p in static-linux cross-mac cross-win cross-arm; do \
	make -C static VERSION=0.0.1-dev GO_VERSION=1.18.5 TARGETPLATFORM= CONTAINERD_VERSION= RUNC_VERSION= ${p}; \
done
make[1]: Entering directory '/home/buczek/git/docker-ce-packaging/static'
cd /home/buczek/git/docker-ce-packaging/src/github.com/docker/cli && VERSION=0.0.0-20220827153212-d89b5db docker buildx bake --set binary.platform= --set binary.args.CGO_ENABLED= binary
/bin/bash: line 1: docker: command not found
make[1]: *** [Makefile:99: static-cli] Error 127
```

**Comment by neersighted** [comment]
This is just the packaging; https://github.com/moby/moby and https://github.com/docker/cli can be compiled as regular programs with no container, if you need to "bootstrap" things from just a Go compiler. You could then install those binaries into your `$PATH`, and then make use of this packaging.

I'm going to close this for now, but please let me know if that's unclear.
