### ISSUE TITLE
ubuntu docker-ce 20.10.17 depends on incorrect containerd.io version

### ISSUE THREAD

**Issue by sm-gravid-day** [docker/docker-ce-packaging#762]
The docker engine release notes here: https://docs.docker.com/engine/release-notes/ state that for engine version 20.10.17 the containerd.io version has been updated to v1.6.6. However, for the following ubuntu packages:

```
5:20.10.17~3-0~ubuntu-bionic
5:20.10.17~3-0~ubuntu-focal
```

Downloading the source and searching the control file shows:

`Depends: containerd.io (>= 1.4.1)`

This can lead to docker-ce upgrades sticking with an existing, older version of containerd.io and missing out on fixes.

Shouldn't the control file be in sync with the release notes?

**Comment by tianon** [comment]
The packaged containerd available in the repository is indeed 1.6.8 now, but the dependency within the engine package is still correct AFAIK -- the engine still works correctly with a 1.4.1+ containerd.  IMO, it would not be appropriate to change this `Depends` just to make sure that users who are not updating all related packages receive the newer version (there may be valid reasons for a user to stick with containerd 1.4.x, for example, but they still want a newer engine).
