### ISSUE TITLE
deb: add support for building debian 12 "Bookworm"

### ISSUE THREAD

**Issue by michaelkrieger** [docker/docker-ce-packaging#793]
With the toolkit freeze for Bookworm being [January 12 2023](https://lists.debian.org/debian-devel-announce/2022/10/msg00004.html) and anticipated freezes only [a month later](https://lists.debian.org/debian-devel/2022/03/msg00251.html), can bookworm be added to the official Docker-CE repository for those testing Bookworm?

**Comment by thaJeztah** [comment]
oh! looks like this was addressed by https://github.com/docker/docker-ce-packaging/pull/838
