### ISSUE TITLE
Debian package lists apparmor as recommended, but doesn't work without it

### ISSUE THREAD

**Issue by markus-k** [docker/docker-ce-packaging#845]
The `docker-ce` Debian package lists `apparmor` as [a recommended dependency](https://github.com/docker/docker-ce-packaging/blob/3c20db63ac41e25c4603171d316735d13557d946/deb/common/control#L34). But since the last update (23.0.0), docker does not work without apparmor.

On a freshly provisioned Debian 11 VM which does not have `apparmor` preinstalled (which is the case for Hetzner Cloud VMs), after installing Docker [as documented](https://docs.docker.com/engine/install/debian/):
```
# docker run --rm -ti debian bash
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
1e4aec178e08: Pull complete
Digest: sha256:43ef0c6c3585d5b406caa7a0f232ff5a19c1402aeb415f68bcd1cf9d10180af8
Status: Downloaded newer image for debian:latest
docker: Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `apparmor_parser apparmor_parser --version` failed with output:
error: exec: "apparmor_parser": executable file not found in $PATH.
ERRO[0004] error waiting for container: context canceled
```

After installing the `apparmor`-package in this VM, running docker containers works as expected.

So either Docker should not require `apparmor` by default, or list it as a required dependency in the debian package.

**Comment by tianon** [comment]
From https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends:

> `Recommends`
> > This declares a strong, but not absolute, dependency.
> >
> > The `Recommends` field should list packages that would be found together with this one in all but unusual installations.

That being said, see also https://github.com/moby/moby/pull/44902 and https://github.com/moby/moby/pull/44942 (which should be released very very soon).

**Comment by neersighted** [comment]
See https://github.com/moby/moby/issues/44970#issuecomment-1426195907 for the latest; we're waiting on a containerd release to fix the root cause.

**Comment by thaJeztah** [comment]
This should be resolved now, but we're considering making this an explicit opt-out (instead of silently ignoring). No changes were made yet though (still to be discussed).
