### ISSUE TITLE
https://download.docker.com/linux/rhel/9/docker-ce.repo stopped working

### ISSUE THREAD

**Issue by lknite** [docker/docker-ce-packaging#862]
I see https://download.docker.com/linux/rhel/docker-ce.repo & tried that, but the urls inside don't work.

Normally I use this repo to install 'containerd'.

**Comment by thaJeztah** [comment]
What architecture are you on? RHEL packages (both for the engine and containerd) are only published for s390x and ppc64le. For other architectures, you can install the CentOS packages; https://docs.docker.com/engine/install/centos/

**Comment by lknite** [comment]
oh, i am switching from centos to rhel, that makes sense... thank you maybe i'll be able to figure this out now

**Comment by thaJeztah** [comment]
Good to hear! Yes, for most scenarios, "CentOS" is still close enough of a match to work with the same version of "RHEL". The RHEL packages for s390x are created by IBM for their customers (and there's no CentOS for s390x).
