### ISSUE TITLE
`docker-compose-plugin` v2.24.6 is not available via apt repos

### ISSUE THREAD

**Issue by AngellusMortis** [docker/docker-ce-packaging#990]
v2.24.5 is still the newest version available via apt repos even though [this PR](https://github.com/docker/docker-ce-packaging/pull/988) was merged a while ago. v2.24.5 is completely broken with Docker Compose files that use `extends` ([issue](https://github.com/docker/compose/issues/11430))

**Comment by thaJeztah** [comment]
Looks like this should be addressed (currently compose 2.26.1 is the latest package); https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/

Deploying of compose packages on download.docker.com is currently coupled with releases of the Docker Engine, so will be published when a new version of the engine is released (which can be a patch release). In future, that process will be decoupled, but that still requires changes to various systems.

I'll close this ticket as this looks to be resolved
